# Generated by Django 4.2.22 — squashed from 0001_initial through 0006

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instance",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("instance_name", models.CharField(max_length=255)),
                ("whitelist_emails", models.TextField(blank=True, null=True)),
                (
                    "instance_id",
                    models.CharField(max_length=255, unique=True),
                ),
                (
                    "current_version",
                    models.CharField(max_length=255),
                ),
                ("last_checked_at", models.DateTimeField()),
                (
                    "namespace",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_telemetry_enabled", models.BooleanField(default=True)),
                ("is_support_required", models.BooleanField(default=True)),
                ("is_setup_done", models.BooleanField(default=False)),
                (
                    "is_signup_screen_visited",
                    models.BooleanField(default=False),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("domain", models.TextField(blank=True)),
                (
                    "latest_version",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "edition",
                    models.CharField(
                        default="QLCV_COMMUNITY", max_length=255
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                ("is_test", models.BooleanField(default=False)),
                (
                    "is_current_version_deprecated",
                    models.BooleanField(default=False),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instance",
                "verbose_name_plural": "Instances",
                "db_table": "instances",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="InstanceConfiguration",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                (
                    "value",
                    models.TextField(blank=True, default=None, null=True),
                ),
                ("category", models.TextField()),
                ("is_encrypted", models.BooleanField(default=False)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instance Configuration",
                "verbose_name_plural": "Instance Configurations",
                "db_table": "instance_configurations",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(max_length=255)),
                ("tags", models.JSONField(default=list)),
                ("release_date", models.DateTimeField(null=True)),
                (
                    "is_release_candidate",
                    models.BooleanField(default=False),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Change Log",
                "verbose_name_plural": "Change Logs",
                "db_table": "changelogs",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="InstanceAdmin",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "role",
                    models.PositiveIntegerField(
                        choices=[(30, "Super Admin")],
                        default=30,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admins",
                        to="license.instance",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instance_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Instance Admin",
                "verbose_name_plural": "Instance Admins",
                "db_table": "instance_admins",
                "ordering": ("-created_at",),
                "unique_together": {("instance", "user")},
            },
        ),
    ]
